
# video_name = 'videos/dashcam/dashcam_126/part%d.mp4'
# num_segments = 61
# num_segments = 61
# collection_name = 'Feb23_encoding_limit_compute'
collection_name = 'Mar26_roi_coco'
enable_cloudseg = false
random_seed = 37
segment_length = 10
input_shape = [720, 1280] # H,W
# qp_matrix_file = '/tank/kuntai/code/qp_matrix_file'
x264_dir = '/datamirror/kuntai/code/myh264/'
compute_limit = 5

[configuration_space]
# left ==> right: expensive ==> cheap
# replicate the right most (the cheapest) configuration twice at the end.
# qp = [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
# res = ['1280x720', '858x480', '480x360', '352x240', '320x180']
# preset = ['veryslow', 'slower', 'slow', 'medium', 'fast', 'faster', 'veryfast', 'superfast', 'ultrafast']
# bf = [1,2,3,4,5,6,7,8,9]

# # b_strategy = [2,1]
# # b_qfactor = [0.0, 0.1, 0.2]
# me_method = ['esa', 'umh', 'hex', 'dia']
# me_range = [16, 14, 12, 10, 8, 6, 4]
# subq = [9,8,7,6,5,4,3,2,1]


# reducto_pixel = [0.2, 0.25, 0.3, 0.35, 0.4]
# reducto_area = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
# reducto_edge = [0.0075, 0.008, 0.0085, 0.009, 0.0095]


[backprop]
lr = 0.1
bw_percentage = 0.1 # 10% of the video in high quality.
# bw_weight = 0.07
# reconstruction_loss_weight = 0.5
train = true # update the configuration or not
# std_score_mean_weight = 0
# compute_weight = 3
# sum_score_mean_wight = 1
app = 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'
early_optimize = true
visualize = false
difference_threshold = 0.25
tile_size = 16
macroblock_shape = [45, 80]
# the QP for macroblock encoding
qps = [24, 26, 28, 30, 34, 36]
saliency_type = 'sigmoid'


    [backprop.frozen_config]

    [backprop.tunable_config]
    # 1: expensive, 0: cheap.
    # reducto_pixel = 1.0
    # reducto_area = 1.0
    # reducto_edge = 1.0

    # qp = 1.0
    # res = 1.0
    # preset = 1.0
    # bf = 1.0
    # me_method = 1.0
    # me_range = 1.0
    # subq = 1.0
    macroblocks = true

    # [backprop.tunable_config_lr]
    # macroblocks = 2000 


    # qp = 0.5
    # res = 0.5
    # fr = 0.5
    # cloudseg = 7e-4
    # app = 'EfficientDet_d2'
    # tunable_configs = ['reducto_pixel', 'reducto_area', 'reducto_edge']
    



[ground_truths_config]
app = 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'
qp = 24
res = '1280x720'
fr = 10
# bf = 1
# me_method = "esa"
# me_range = 16
# subq = 9
# preset = "veryslow"


[inference_config]
force_inference = false
enable_visualization = false
visualize_step_size = 1

[examine_config]
force_examine = false




[postprocess]
size_threshold = 0.08



[COCO-Detection_faster_rcnn_R_101_FPN_3x_yaml]
confidence_threshold = 0.5
gt_confidence_threshold = 0.5
# let's only care about cars
class_ids = [2]
size_threshold = 0.05
iou_threshold = 0.5